name: update-release-notes

# Controls when the workflow will run
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "PR ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }}) has been merged"
        closed_pr="- ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
        closed_pr_lower=$(echo "$closed_pr" | sed -e 's/\(.*\)/\L\1/')
        gh repo clone $GITHUB_REPOSITORY
        REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F ["/"] '{print $2}')
        echo $REPO_NAME
      env:
        GH_TOKEN: ${{ secrets.GIT_TOKEN }}
